name: .NET Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    matrix:
      configuration: [Debug, Release]
      runtime: [win-x64, win-x86, linux-x64]
      dotnet-version: [ '8.0' ]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish -a x64 -p:PublishSingleFile=true

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.configuration }}-${{ matrix.runtime }}
        path: bin/${{ matrix.configuration }}/net${{ matrix.dotnet-version }}/${{ matrix.runtime }}/publish
